apiVersion: v1
kind: Secret
metadata:
  name: git
  labels:
    app: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.airflow.dags.git.username }}
  GIT_SYNC_USERNAME: {{ .Values.airflow.dags.git.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.airflow.dags.git.password }}
  GIT_SYNC_PASSWORD: {{ .Values.airflow.dags.git.password | b64enc | quote }}
  {{- end}}
  {{- if .Values.airflow.dags.git.rev }}
  GIT_SYNC_REV: {{ .Values.airflow.dags.git.rev | b64enc | quote }}
  {{- end}}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: webserver-config
  labels:
    app: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  webserver_config.py: {{ .Values.airflow.rbac.webserver_config | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "airflow.fullname" . }}-env
  labels:
    app: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: {{ printf "mysql://%s:%s@%s:%.0f/%s" .Values.mysql.db.user .Values.mysql.db.password (include "airflow.mysql.fullname" .) .Values.mysql.service.port .Values.mysql.db.name | b64enc | quote }}
  AIRFLOW__CORE__EXECUTOR: S3ViZXJuZXRlc0V4ZWN1dG9y
  AIRFLOW_HOME: {{ printf "/usr/local/airflow" | b64enc | quote }}
  {{- if not .Values.airflow.dags.persistence.enabled }}
  {{- if .Values.airflow.dags.git.username }}
  AIRFLOW__KUBERNETES__GIT_USER: {{ .Values.airflow.dags.git.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.airflow.dags.git.password }}
  AIRFLOW__KUBERNETES__GIT_PASSWORD: {{ .Values.airflow.dags.git.password | b64enc | quote }}
  {{- end }}
  {{- end }}
  FERNET_KEY: {{ .Values.airflow.fernet_key | b64enc | quote }}
  {{- range $setting, $option := .Values.airflow.config }}
  {{ $setting }}: {{ $option | b64enc | quote }}
  {{- end }}

  # For puckel/docker-airflow
  MYSQL_HOST: {{ include "airflow.mysql.fullname" . | b64enc | quote }}
  MYSQL_USER: {{ .Values.mysql.db.user | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.db.password | b64enc | quote }}
  MYSQL_DB: {{ .Values.mysql.db.name | b64enc | quote }}

